---
title: "alc_corr_dietguthealth"
author: "Yasmine"
date: "2024-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(rcompanion)
```

```{r data}

df_c <- read.csv("/Users/yasmine.bouzid/Desktop/GraduateWork/DataScience/Dairy_GutHealth/data/df_c_sc.csv", header = T) # n = 295, check. 

df_m <- read.csv("/Users/yasmine.bouzid/Desktop/GraduateWork/DataScience/Dairy_GutHealth/data/df_m_sc.csv", header = T) # n = 295, check. 

df_n <- read.csv("/Users/yasmine.bouzid/Desktop/GraduateWork/DataScience/Dairy_GutHealth/data/df_n_sc.csv", header = T) # 289, check. 

# and normalize:

df_n$nptn_boxcox <- (bestNormalize::boxcox(df_n$fecal_neopterin))$x.t

df_l <- read.csv(file = "/Users/yasmine.bouzid/Desktop/GraduateWork/DataScience/Dairy_GutHealth/data/df_gh_l_rd.csv", header = TRUE) #348, check. 

# And fix the structure of things 

df_c$subject_id <- as.factor(as.character(df_c$subject_id))
df_c$sex <- df_c$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_c$age_cat <- df_c$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_c$bmi_cat <- df_c$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")
df_c$AfterV2 <- df_c$AfterV2 %>% recode_factor('0' = "No", '1' = "Yes")

df_m$subject_id <- as.factor(as.character(df_m$subject_id))
df_m$sex <- df_m$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_m$age_cat <- df_m$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_m$bmi_cat <- df_m$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")
df_m$AfterV2 <- df_m$AfterV2 %>% recode_factor('0' = "No", '1' = "Yes")

df_n$subject_id <- as.factor(as.character(df_n$subject_id))
df_n$sex <- df_n$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_n$age_cat <- df_n$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_n$bmi_cat <- df_n$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")
df_n$AfterV2 <- df_n$AfterV2 %>% recode_factor('0' = "No", '1' = "Yes")

df_l$subject_id <- as.factor(as.character(df_l$subject_id))
df_l$sex <- df_l$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_l$age_cat <- df_l$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_l$bmi_cat <- df_l$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

# READY FOR LIFT OFF

```

Import the alcohol data and append 

```{r alc-data}

# Import

alc <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/forR_alcohol.csv", header = T)

# Append to the GIM dataframes 

df_c <- merge(df_c, alc, by = 'subject_id')
df_m <- merge(df_m, alc, by = 'subject_id')
df_n <- merge(df_n, alc, by = 'subject_id')
df_l <- merge(df_l, alc, by = 'subject_id')

# There are extra columns called X, X.1 etc. Not sure why, delete them 

df_c <- df_c[ , c(1:73)]
df_m <- df_m[ , c(1:73)]
df_n <- df_n[ , c(1:73)]
df_l <- df_l[ , c(1:69)]

```

Next, let's look at the association between alcohol consumption reported in 24h with GIM



```{r corr-asa24-alc}

# for ASA24, alcohol in grams is called alc

# Look at the distribution for alc
plot(df_c$alc, df_c$Stool.calprotectin) # zero inflated

# Calprotectin

mod_c_alc <- lm(clpn_ln ~ alc + age + sex + bmi_final, data = df_c)
summary(mod_c_alc) # NS

# make the regression plot 

ggplotRegression_c_alc <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: ASA24 Alcohol vs. Calprotectin (n = 295)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed Calprotectin (ln(x + 1))") +
  theme_bw()
}

ggplotRegression_c_alc(mod_c_alc)

c_alc_mx <- ggplotRegression_c_alc(mod_c_alc) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/c_alc_mx.jpeg', c_alc_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)



# Myeloperoxidase

mod_m_alc <- lm(mpo_ln ~ alc + age + sex + bmi_final, data = df_m)
summary(mod_m_alc) # NS


# make the regression plot 

ggplotRegression_m_alc <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: ASA24 Alcohol vs. Myeloperoxidase (n = 295)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed Myeloperoxidase (ln(x + 3))") +
  theme_bw()
}

ggplotRegression_m_alc(mod_m_alc)

m_alc_mx <- ggplotRegression_m_alc(mod_m_alc) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/m_alc_mx.jpeg', m_alc_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)




# Neopterin

mod_n_alc <- lm(nptn_boxcox ~ alc + age + sex + bmi_final, data = df_n)
summary(mod_n_alc) # NS


# make the regression plot 

ggplotRegression_n_alc <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: ASA24 Alcohol vs. Neopterin (n = 289)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed Neopterin (Box Cox)") +
  theme_bw()
}

ggplotRegression_n_alc(mod_n_alc)

n_alc_mx <- ggplotRegression_n_alc(mod_n_alc) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/n_alc_mx.jpeg', n_alc_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)



# LPS-binding protein (LBP)

mod_l_alc <- lm(lbp_ln ~ alc + age + sex + bmi_final, data = df_l)
summary(mod_l_alc) # NS


# make the regression plot 

ggplotRegression_l_alc <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: ASA24 Alcohol vs. LBP (n = 348)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed LBP (ln(x + 1))") +
  theme_bw()
}

ggplotRegression_l_alc(mod_l_alc)

l_alc_mx <- ggplotRegression_l_alc(mod_l_alc) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/l_alc_mx.jpeg', l_alc_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)

# Save in a grid format 

alc_mx <- ggarrange(c_alc_mx, m_alc_mx, n_alc_mx, l_alc_mx,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/grid_alc_mx.jpeg', plot = alc_mx, device = 'jpeg', dpi = 300, width = 15, height = 10)


```

Now let's look at alcohol association with alcohol reported in FFQ 


```{r corr-ffq-alc}

# for FFQ, alcohol in grams is called dt_alco

# Look at the distribution for dt_alco
plot(df_c$dt_alco, df_c$Stool.calprotectin) # zero inflated

# Calprotectin

mod_c_dt_alco <- lm(clpn_ln ~ dt_alco + age + sex + bmi_final, data = df_c)
summary(mod_c_dt_alco) # NS

# make the regression plot 

ggplotRegression_c_dt_alco <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: FFQ Alcohol vs. Calprotectin (n = 295)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed Calprotectin (ln(x + 1))") +
  theme_bw()
}

ggplotRegression_c_dt_alco(mod_c_dt_alco)

c_dt_alco_mx <- ggplotRegression_c_dt_alco(mod_c_dt_alco) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/c_dt_alco_mx.jpeg', c_dt_alco_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)



# Myeloperoxidase

mod_m_dt_alco <- lm(mpo_ln ~ dt_alco + age + sex + bmi_final, data = df_m)
summary(mod_m_dt_alco) # NS


# make the regression plot 

ggplotRegression_m_dt_alco <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: FFQ Alcohol vs. Myeloperoxidase (n = 295)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed Myeloperoxidase (ln(x + 3))") +
  theme_bw()
}

ggplotRegression_m_dt_alco(mod_m_dt_alco)

m_dt_alco_mx <- ggplotRegression_m_dt_alco(mod_m_dt_alco) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/m_dt_alco_mx.jpeg', m_dt_alco_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)




# Neopterin

mod_n_dt_alco <- lm(nptn_boxcox ~ dt_alco + age + sex + bmi_final, data = df_n)
summary(mod_n_dt_alco) # NS


# make the regression plot 

ggplotRegression_n_dt_alco <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: FFQ Alcohol vs. Neopterin (n = 289)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed Neopterin (Box Cox)") +
  theme_bw()
}

ggplotRegression_n_dt_alco(mod_n_dt_alco)

n_dt_alco_mx <- ggplotRegression_n_dt_alco(mod_n_dt_alco) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/n_dt_alco_mx.jpeg', n_dt_alco_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)



# LPS-binding protein (LBP)

mod_l_dt_alco <- lm(lbp_ln ~ dt_alco + age + sex + bmi_final, data = df_l)
summary(mod_l_dt_alco) # NS


# make the regression plot 

ggplotRegression_l_dt_alco <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Mixed Model: FFQ Alcohol vs. LBP (n = 348)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     ", Intercept = ",signif(fit$coef[[1]],5 ),
                     ", Slope = ",signif(fit$coef[[2]], 5),
                     ", P = ",signif(summary(fit)$coef[2,4], 5)),
       x = "Alcohol/day (grams)",
       y = "Transformed LBP (ln(x + 1))") +
  theme_bw()
}

ggplotRegression_l_dt_alco(mod_l_dt_alco)

l_dt_alco_mx <- ggplotRegression_l_dt_alco(mod_l_dt_alco) 

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/l_dt_alco_mx.jpeg', l_dt_alco_mx, device = 'jpeg', dpi = 300, width = 7, height = 5)

# Save in a grid format 

dt_alco_mx <- ggarrange(c_dt_alco_mx, m_dt_alco_mx, n_dt_alco_mx, l_dt_alco_mx,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/grid_dt_alco_mx.jpeg', plot = dt_alco_mx, device = 'jpeg', dpi = 300, width = 15, height = 10)


```

**Summary of findings**: 

- ASA24 alcohol consumption barely associated with LBP: P = 0.046, negative slope
- No significant associations between FFQ alcohol and GIM