---
title: "table1_dietguthealth"
author: "Yasmine"
date: "2024-01-12"
output: html_document
---

Multiple hypoth test correction for Table 3

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

```{r import}

df_c <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_c.csv", header = T)

df_m <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_m.csv", header = T)

df_n <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_n.csv", header = T)

df_l <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_l.csv", header = T)

# unfortunately, need to correct structure of some variables each time -->

df_c$subject_id <- as.factor(as.character(df_c$subject_id))
df_c$sex <- df_c$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_c$age_cat <- df_c$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_c$bmi_cat <- df_c$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

df_m$subject_id <- as.factor(as.character(df_m$subject_id))
df_m$sex <- df_m$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_m$age_cat <- df_m$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_m$bmi_cat <- df_m$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

df_n$subject_id <- as.factor(as.character(df_n$subject_id))
df_n$sex <- df_n$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_n$age_cat <- df_n$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_n$bmi_cat <- df_n$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

df_l$subject_id <- as.factor(as.character(df_l$subject_id))
df_l$sex <- df_l$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_l$age_cat <- df_l$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_l$bmi_cat <- df_l$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

```

Models used for analysis: regression of transformed GI inflammation marker ~ dietary component
Covariates: age, sex, BMI

Starting with total HEI scores

```{r asa24-hei}

# Calprotectin

mod_hei_asa24_totalscore_c <- lm(clpn_ln ~ hei_asa24_totalscore + age + sex + bmi_final, data = df_c)
summary(mod_hei_asa24_totalscore_c) # NS

# Myeloperoxidase

mod_hei_asa24_totalscore_m <- lm(mpo_ln ~ hei_asa24_totalscore + age + sex + bmi_final, data = df_m)
summary(mod_hei_asa24_totalscore_m) # NS

# Neopterin

mod_hei_asa24_totalscore_n <- lm(nptn_boxcox ~ hei_asa24_totalscore + age + sex + bmi_final, data = df_n)
summary(mod_hei_asa24_totalscore_n) # 

# LBP

mod_hei_asa24_totalscore_l <- lm(lbp_ln ~ hei_asa24_totalscore + age + sex + bmi_final, data = df_l)
summary(mod_hei_asa24_totalscore_l) # NS

# Extract p-values 
p_c_hei_asa24_totalscore <- summary(mod_hei_asa24_totalscore_c)$coefficients[2,4] 
p_m_hei_asa24_totalscore <- summary(mod_hei_asa24_totalscore_m)$coefficients[2,4]
p_n_hei_asa24_totalscore <- summary(mod_hei_asa24_totalscore_n)$coefficients[2,4]
p_l_hei_asa24_totalscore <- summary(mod_hei_asa24_totalscore_l)$coefficients[2,4]

```
Total HEI scores (ffq)

```{r ffq-hei}

# Calprotectin

mod_hei_ffq_totalscore_c <- lm(clpn_ln ~ hei_ffq_totalscore + age + sex + bmi_final, data = df_c)
summary(mod_hei_ffq_totalscore_c) # NS

# Myeloperoxidase

mod_hei_ffq_totalscore_m <- lm(mpo_ln ~ hei_ffq_totalscore + age + sex + bmi_final, data = df_m)
summary(mod_hei_ffq_totalscore_m) # NS

# Neopterin

mod_hei_ffq_totalscore_n <- lm(nptn_boxcox ~ hei_ffq_totalscore + age + sex + bmi_final, data = df_n)
summary(mod_hei_ffq_totalscore_n) # 

# LBP

mod_hei_ffq_totalscore_l <- lm(lbp_ln ~ hei_ffq_totalscore + age + sex + bmi_final, data = df_l)
summary(mod_hei_ffq_totalscore_l) # NS

# Extract p-values 
p_c_hei_ffq_totalscore <- summary(mod_hei_ffq_totalscore_c)$coefficients[2,4] 
p_m_hei_ffq_totalscore <- summary(mod_hei_ffq_totalscore_m)$coefficients[2,4]
p_n_hei_ffq_totalscore <- summary(mod_hei_ffq_totalscore_n)$coefficients[2,4]
p_l_hei_ffq_totalscore <- summary(mod_hei_ffq_totalscore_l)$coefficients[2,4]


```

Last, we'll look at DII scores

```{r asa24-dii}

# Calprotectin

mod_dii_asa24_total_score_c <- lm(clpn_ln ~ dii_asa24_total_score + age + sex + bmi_final, data = df_c)
summary(mod_dii_asa24_total_score_c) # NS

# Myeloperoxidase

mod_dii_asa24_total_score_m <- lm(mpo_ln ~ dii_asa24_total_score + age + sex + bmi_final, data = df_m)
summary(mod_dii_asa24_total_score_m) # NS

# Neopterin

mod_dii_asa24_total_score_n <- lm(nptn_boxcox ~ dii_asa24_total_score + age + sex + bmi_final, data = df_n)
summary(mod_dii_asa24_total_score_n) # NS

# LBP

mod_dii_asa24_total_score_l <- lm(lbp_ln ~ dii_asa24_total_score + age + sex + bmi_final, data = df_l)
summary(mod_dii_asa24_total_score_l) # NS

# Extract p-values 
p_c_dii_asa24_total_score <- summary(mod_dii_asa24_total_score_c)$coefficients[2,4] 
p_m_dii_asa24_total_score <- summary(mod_dii_asa24_total_score_m)$coefficients[2,4]
p_n_dii_asa24_total_score <- summary(mod_dii_asa24_total_score_n)$coefficients[2,4]
p_l_dii_asa24_total_score <- summary(mod_dii_asa24_total_score_l)$coefficients[2,4]


```

```{r ffq-dii}

# Calprotectin

mod_dii_ffq_total_score_c <- lm(clpn_ln ~ dii_ffq_total_score + age + sex + bmi_final, data = df_c)
summary(mod_dii_ffq_total_score_c) # NS

# Myeloperoxidase

mod_dii_ffq_total_score_m <- lm(mpo_ln ~ dii_ffq_total_score + age + sex + bmi_final, data = df_m)
summary(mod_dii_ffq_total_score_m) # NS

# Neopterin

mod_dii_ffq_total_score_n <- lm(nptn_boxcox ~ dii_ffq_total_score + age + sex + bmi_final, data = df_n)
summary(mod_dii_ffq_total_score_n) # NS

# LBP

mod_dii_ffq_total_score_l <- lm(lbp_ln ~ dii_ffq_total_score + age + sex + bmi_final, data = df_l)
summary(mod_dii_ffq_total_score_l) # NS

# Extract p-values 
p_c_dii_ffq_total_score <- summary(mod_dii_ffq_total_score_c)$coefficients[2,4] 
p_m_dii_ffq_total_score <- summary(mod_dii_ffq_total_score_m)$coefficients[2,4]
p_n_dii_ffq_total_score <- summary(mod_dii_ffq_total_score_n)$coefficients[2,4]
p_l_dii_ffq_total_score <- summary(mod_dii_ffq_total_score_l)$coefficients[2,4]


```
```{r p-test-df}

# Import the data frames

c_asa_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/c_asa_pk_pval_df.csv", header = T)
m_asa_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/m_asa_pk_pval_df.csv", header = T)
n_asa_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/n_asa_pk_pval_df.csv", header = T)
l_asa_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/l_asa_pk_pval_df.csv", header = T)

c_ffq_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/c_ffq_pk_pval_df.csv", header = T)
m_ffq_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/m_ffq_pk_pval_df.csv", header = T)
n_ffq_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/n_ffq_pk_pval_df.csv", header = T)
l_ffq_pk_pval_df <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/l_ffq_pk_pval_df.csv", header = T)

# Collating the p-vals into a df for future multiple hypothesis test correction 

c_asa_pk_pval_df_t <- data.frame(p_c_hei_asa24_totalscore, p_c_dii_asa24_total_score)
c_ffq_pk_pval_df_t <- data.frame(p_c_hei_ffq_totalscore, p_c_dii_ffq_total_score)

m_asa_pk_pval_df_t <- data.frame(p_m_hei_asa24_totalscore, p_m_dii_asa24_total_score)
m_ffq_pk_pval_df_t <- data.frame(p_m_hei_ffq_totalscore, p_m_dii_ffq_total_score)

n_asa_pk_pval_df_t <- data.frame(p_n_hei_asa24_totalscore, p_n_dii_asa24_total_score)
n_ffq_pk_pval_df_t <- data.frame(p_n_hei_ffq_totalscore, p_n_dii_ffq_total_score)

l_asa_pk_pval_df_t <- data.frame(p_l_hei_asa24_totalscore, p_l_dii_asa24_total_score)
l_ffq_pk_pval_df_t <- data.frame(p_l_hei_ffq_totalscore, p_l_dii_ffq_total_score)

# Merge 

c_asa_pk_pval_df <- merge(c_asa_pk_pval_df, c_asa_pk_pval_df_t)
c_ffq_pk_pval_df <- merge(c_ffq_pk_pval_df, c_ffq_pk_pval_df_t)

m_asa_pk_pval_df <- merge(m_asa_pk_pval_df, m_asa_pk_pval_df_t)
m_ffq_pk_pval_df <- merge(m_ffq_pk_pval_df, m_ffq_pk_pval_df_t)

n_asa_pk_pval_df <- merge(n_asa_pk_pval_df, n_asa_pk_pval_df_t)
n_ffq_pk_pval_df <- merge(n_ffq_pk_pval_df, n_ffq_pk_pval_df_t)

l_asa_pk_pval_df <- merge(l_asa_pk_pval_df, l_asa_pk_pval_df_t)
l_ffq_pk_pval_df <- merge(l_ffq_pk_pval_df, l_ffq_pk_pval_df_t)

# Export

write.csv(c_asa_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/c_asa_pk_pval_df.csv", row.names = T)
write.csv(c_ffq_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/c_ffq_pk_pval_df.csv", row.names = T)

write.csv(m_asa_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/m_asa_pk_pval_df.csv", row.names = T)
write.csv(m_ffq_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/m_ffq_pk_pval_df.csv", row.names = T)

write.csv(n_asa_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/n_asa_pk_pval_df.csv", row.names = T)
write.csv(n_ffq_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/n_ffq_pk_pval_df.csv", row.names = T)

write.csv(l_asa_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/l_asa_pk_pval_df.csv", row.names = T)
write.csv(l_ffq_pk_pval_df, "/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/l_ffq_pk_pval_df.csv", row.names = T)

```

**Summary of Findings**: 

- 