---
title: "table1_dietguthealth"
author: "Yasmine"
date: "2024-01-12"
output: html_document
---

Running statistics to see associations between fiber and gut health (Table 1)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)

```

```{r import}

df_c <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_c.csv", header = T)

# Label based off the clinical designation levels

df_c$clin_level_clpn[df_c$Stool.calprotectin < 50] <- "negative"

df_c$clin_level_clpn[df_c$Stool.calprotectin >= 50 & df_c$Stool.calprotectin <= 100] <- "bord_positive"

df_c$clin_level_clpn[df_c$Stool.calprotectin > 100] <- "positive"

# Convert variable type to factor, and order them 
df_c$clin_level_clpn <- factor(df_c$clin_level_clpn, ordered = T,
                                  c("negative", "bord_positive", "positive"))

table(df_c$clin_level_clpn)

df_c_s <- df_c %>% filter(clin_level_clpn != "positive") # n = 253, check. 

df_c <- df_c_s
rm(df_c_s)


# unfortunately, need to correct structure of some variables each time -->

df_c$subject_id <- as.factor(as.character(df_c$subject_id))
df_c$sex <- df_c$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_c$age_cat <- df_c$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_c$bmi_cat <- df_c$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

```

Models used for analysis: regression of transformed GI inflammation marker ~ dietary component
Covariates: age, sex, BMI

Creating plots to show regression curves for associations between diet components and subclincial calprotectin

```{r ffq-fiber}

# Calprotectin

# Create dt_fibe_pk (pk = per 1000 kcal)

df_c$dt_fibe_pk <- df_c$dt_fibe/(df_c$kcal/1000)

mod_dt_fibe_pk_c <- lm(clpn_ln ~ dt_fibe_pk + age + sex + bmi_final, data = df_c)
summary(mod_dt_fibe_pk_c) # P = 0.0285 *  

# Calprotectin

# x - axis (independent variable res)
mod_ffq_fib <- lm(dt_fibe_pk ~ age + sex + bmi_final, data = df_c)
df_c$mod_ffq_fib_residuals <- residuals(mod_ffq_fib)

# y - axis (dependent variable res)
mod_clpn <- lm(clpn_ln ~ age + sex + bmi_final, data = df_c)
df_c$mod_clpn_residuals <- residuals(mod_clpn)

# create the plot 

fig4_partregfib_clpn <-
  ggplot(df_c, aes(x = mod_ffq_fib_residuals, y = mod_clpn_residuals)) +
  geom_point() + 
  geom_smooth(method = 'lm', color = 'blue') + 
  labs(title = "Subclinical Calprotectin ~ Habitual Fiber + Age + Sex + BMI (n = 253)") +
  labs(subtitle = "Adj R-squared = 0.065, Beta = -0.033, P = 0.0002") +
  labs(caption = "Holding covariates constant") + 
  xlab("Fiber Intake (model residuals)") + 
  ylab("Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
   theme(text = element_text(size = 14),
        plot.title = element_text(size = 18),
           axis.title = element_text(size = 16),
           axis.text = element_text(size = 14),
        plot.margin = margin(10, 25, 10, 20, unit = "pt"))

```

```{r ffq-legumes}

# Calprotectin

# Create v_legumes.y_pk (pk = per 1000 kcal)

df_c$v_legumes.y_pk <- df_c$v_legumes.y/(df_c$kcal/1000)

mod_v_legumes.y_pk_c <- lm(clpn_ln ~ v_legumes.y_pk + age + sex + bmi_final, data = df_c)
summary(mod_v_legumes.y_pk_c) #  

# Calprotectin

# x - axis (independent variable res)
mod_ffq_leg <- lm(v_legumes.y_pk ~ age + sex + bmi_final, data = df_c)
df_c$mod_ffq_leg_residuals <- residuals(mod_ffq_leg)

# y - axis (dependent variable res)
mod_clpn <- lm(clpn_ln ~ age + sex + bmi_final, data = df_c)
df_c$mod_clpn_residuals <- residuals(mod_clpn)

# create the plot 

fig4_partregleg_clpn <-
  ggplot(df_c, aes(x = mod_ffq_leg_residuals, y = mod_clpn_residuals)) +
  geom_point() + 
  geom_smooth(method = 'lm', color = 'blue') + 
  labs(title = "Subclinical Calprotectin ~ Habitual Legumes + Age + Sex + BMI (n = 253)") +
  labs(subtitle = "Adj R-squared = 0.044, Beta = -1.01, P = 0.001") +
  labs(caption = "Holding covariates constant") + 
  xlab("Legume Intake (model residuals)") + 
  ylab("Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
   theme(text = element_text(size = 14),
        plot.title = element_text(size = 18),
           axis.title = element_text(size = 16),
           axis.text = element_text(size = 14),
        plot.margin = margin(10, 25, 10, 20, unit = "pt"))


```

```{r ffq-v-t-total}

# Calprotectin

# Create v_t_total.y_pk (pk = per 1000 kcal)

df_c$v_t_total.y_pk <- df_c$v_t_total.y/(df_c$kcal/1000)

mod_v_t_total.y_pk_c <- lm(clpn_ln ~ v_t_total.y_pk + age + sex + bmi_final, data = df_c)
summary(mod_v_t_total.y_pk_c) # NS

# Calprotectin

# x - axis (independent variable res)
mod_ffq_veg <- lm(v_t_total.y_pk ~ age + sex + bmi_final, data = df_c)
df_c$mod_ffq_veg_residuals <- residuals(mod_ffq_veg)

# y - axis (dependent variable res)
mod_clpn <- lm(clpn_ln ~ age + sex + bmi_final, data = df_c)
df_c$mod_clpn_residuals <- residuals(mod_clpn)

# create the plot 

fig4_partregveg_clpn <-
  ggplot(df_c, aes(x = mod_ffq_veg_residuals, y = mod_clpn_residuals)) +
  geom_point() + 
  geom_smooth(method = 'lm', color = 'blue') + 
  labs(title = "Subclinical Calprotectin ~ Habitual Vegetables + Age + Sex + BMI (n = 253)") +
  labs(subtitle = "Adj R-squared = 0.043, Beta = -0.19, P = 0.001") +
  labs(caption = "Holding covariates constant") + 
  xlab("Total Vegetable Intake (model residuals)") + 
  ylab("Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
   theme(text = element_text(size = 14),
        plot.title = element_text(size = 18),
           axis.title = element_text(size = 16),
           axis.text = element_text(size = 14),
        plot.margin = margin(10, 25, 10, 20, unit = "pt"))

```


```{r asa24-hei}

# Calprotectin

mod_hei_asa24_totalscore_c <- lm(clpn_ln ~ hei_asa24_totalscore + age + sex + bmi_final, data = df_c)
summary(mod_hei_asa24_totalscore_c) # NS

# Calprotectin

# x - axis (independent variable res)
mod_asa24_hei <- lm(hei_asa24_totalscore ~ age + sex + bmi_final, data = df_c)
df_c$mod_asa24_hei_residuals <- residuals(mod_ffq_hei)

# y - axis (dependent variable res)
mod_clpn <- lm(clpn_ln ~ age + sex + bmi_final, data = df_c)
df_c$mod_clpn_residuals <- residuals(mod_clpn)

# create the plot 

fig4_partreghei_clpn <-
  ggplot(df_c, aes(x = mod_asa24_hei_residuals, y = mod_clpn_residuals)) +
  geom_point() + 
  geom_smooth(method = 'lm', color = 'blue') + 
  labs(title = "Subclinical Calprotectin ~ Recent HEI Score + Age + Sex + BMI (n = 253)") +
  labs(subtitle = "Adj R-squared = 0.039, Beta = -0.013, P = 0.003") +
  labs(caption = "Holding covariates constant") + 
  xlab("Total Healthy Eating Index Score (model residuals)") + 
  ylab("Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
   theme(text = element_text(size = 14),
        plot.title = element_text(size = 18),
           axis.title = element_text(size = 16),
           axis.text = element_text(size = 14),
        plot.margin = margin(10, 25, 10, 20, unit = "pt"))

```

```{r grid-save}

# Grid and save: 


fig4_partreg <- ggarrange(fig4_partregfib_clpn, fig4_partregleg_clpn, fig4_partregveg_clpn, fig4_partreghei_clpn,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/fig4_partreg.jpg', plot = fig4_partreg, device = 'jpeg', dpi = 300, width = 21, height = 14, units = "in")

```

