---
title: "table1_dietguthealth"
author: "Yasmine"
date: "2024-01-12"
output: html_document
---

Partial regression for figure 4

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(car)
library(effects)

```

```{r import}

df_c <- read.csv("/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/data/df_c.csv", header = T)

# Label based off the clinical designation levels

df_c$clin_level_clpn[df_c$Stool.calprotectin < 50] <- "negative"

df_c$clin_level_clpn[df_c$Stool.calprotectin >= 50 & df_c$Stool.calprotectin <= 100] <- "bord_positive"

df_c$clin_level_clpn[df_c$Stool.calprotectin > 100] <- "positive"

# Convert variable type to factor, and order them 
df_c$clin_level_clpn <- factor(df_c$clin_level_clpn, ordered = T,
                                  c("negative", "bord_positive", "positive"))

table(df_c$clin_level_clpn)

df_c_s <- df_c %>% filter(clin_level_clpn != "positive") # n = 253, check. 

df_c <- df_c_s
rm(df_c_s)


# unfortunately, need to correct structure of some variables each time -->

df_c$subject_id <- as.factor(as.character(df_c$subject_id))
df_c$sex <- df_c$sex %>% recode_factor('1' = 'Male', '2' = "Female")
df_c$age_cat <- df_c$age_cat %>% recode_factor('1' = '18-33.99 years', '2' = "34-49.99 years", '3' = "50-65 years")
df_c$bmi_cat <- df_c$bmi_cat %>% recode_factor('1' = 'Normal', '2' = "Overweight", '3' = "Obese")

```

Models used for analysis: regression of transformed GI inflammation marker ~ dietary component
Covariates: age, sex, BMI

Creating plots to show regression curves for associations between diet components and subclincial calprotectin

```{r ffq-fiber}

# Calprotectin

mod_dt_fibe_c <- lm(clpn_ln ~ dt_fibe + age + sex + bmi_final, data = df_c)
summary(mod_dt_fibe_c) # P = 0.0285 *  




# make the regression plot 

ggplotRegression_c_fib <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Habitual Fiber Intake vs. Subclinical Calprotectin (n = 253)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 2),
                     ", Slope = ",signif(fit$coef[[2]], 2),
                     ", P = ",signif(summary(fit)$coef[2,4], 2)),
       x = "Fiber (grams/day)",
       y = "Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
  theme(text = element_text(size = 13),
        plot.title = element_text(size = 20),
           axis.title = element_text(size = 18),
           axis.text = element_text(size = 15))
}

ggplotRegression_c_fib(mod_dt_fibe_c)

c_fib_reg <- ggplotRegression_c_fib(mod_dt_fibe_c)

# Partial regression to remove confounding effect from partial residuals 

car::avPlots(mod_dt_fibe_c, pch = 16, col.lines = "blue")
# actually I think I'll use the effects package for better visualization 

# Look at all predictors
plot(allEffects(mod_dt_fibe_c, residuals = T)) 

eff_fib_fib <- plot(allEffects(mod_dt_fibe_c, residuals = T), 
     selection = 1, 
     main = 'Partial Regression Habitual Fiber Intake vs. Subclinical Calprotectin', 
     xlab = 'Fiber (grams/day)', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_fib_age <- plot(allEffects(mod_dt_fibe_c, residuals = T), 
     selection = 2, 
     main = 'Partial Regression for Age (Habitual Fiber Intake vs. Subclinical Calprotectin)', 
     xlab = 'Age (years)', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_fib_sex <- plot(allEffects(mod_dt_fibe_c, residuals = T), 
     selection = 3, 
     main = 'Partial Regression for Sex (Habitual Fiber Intake vs. Subclinical Calprotectin)', 
     xlab = 'Sex', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_fib_bmi <- plot(allEffects(mod_dt_fibe_c, residuals = T), 
     selection = 4, 
     main = 'Partial Regression for BMI (Habitual Fiber Intake vs. Subclinical Calprotectin)', 
     xlab = expression('BMI (kg/m'^2*')'),
     ylab = 'Transformed Calprotectin (ln(x + 1)')

# Grid and save 

fig4_par_fib <- ggarrange(eff_fib_fib, eff_fib_age, eff_fib_sex, eff_fib_bmi,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/fig4_par_fib.jpg', plot = fig4_par_fib, device = 'jpeg', dpi = 300, width = 20, height = 10)

```

```{r ffq-legumes}

# Calprotectin

mod_v_legumes.y_c <- lm(clpn_ln ~ v_legumes.y + age + sex + bmi_final, data = df_c)
summary(mod_v_legumes.y_c) #  

# make the regression plot 

ggplotRegression_c_leg <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Habitual Legume Intake vs. Subclinical Calprotectin (n = 253)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 2),
                     ", Slope = ",signif(fit$coef[[2]], 2),
                     ", P = ",signif(summary(fit)$coef[2,4], 2)),
       x = "Legumes (cup eq/day)",
       y = "Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
  theme(text = element_text(size = 13),
        plot.title = element_text(size = 20),
           axis.title = element_text(size = 18),
           axis.text = element_text(size = 15))
}

ggplotRegression_c_leg(mod_v_legumes.y_c)

c_leg_reg <- ggplotRegression_c_leg(mod_v_legumes.y_c)

# Partial regression 

# Look at all predictors
plot(allEffects(mod_v_legumes.y_c, residuals = T)) 

eff_leg_leg <- plot(allEffects(mod_v_legumes.y_c, residuals = T), 
     selection = 1, 
     main = 'Partial Regression Habitual Legume Intake vs. Subclinical Calprotectin', 
     xlab = 'Legumes (grams/day)', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_leg_age <- plot(allEffects(mod_v_legumes.y_c, residuals = T), 
     selection = 2, 
     main = 'Partial Regression for Age (Habitual Legume Intake vs. Subclinical Calprotectin)', 
     xlab = 'Age (years)', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_leg_sex <- plot(allEffects(mod_v_legumes.y_c, residuals = T), 
     selection = 3, 
     main = 'Partial Regression for Sex (Habitual Legume Intake vs. Subclinical Calprotectin)', 
     xlab = 'Sex', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_leg_bmi <- plot(allEffects(mod_v_legumes.y_c, residuals = T), 
     selection = 4, 
     main = 'Partial Regression for BMI (Habitual Legume Intake vs. Subclinical Calprotectin)', 
     xlab = expression('BMI (kg/m'^2*')'),
     ylab = 'Transformed Calprotectin (ln(x + 1)')

# Grid and save 

fig4_par_leg <- ggarrange(eff_leg_leg, eff_leg_age, eff_leg_sex, eff_leg_bmi,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/fig4_par_leg.jpg', plot = fig4_par_leg, device = 'jpeg', dpi = 300, width = 20, height = 10)


```

```{r asa24-sfat}

# Calprotectin

mod_sfat_c <- lm(clpn_ln ~ sfat + age + sex + bmi_final, data = df_c)
summary(mod_sfat_c) # NS

# make the regression plot 

ggplotRegression_c_sfat <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Recent Saturated Fat Intake vs. Subclinical Calprotectin (n = 253)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 2),
                     ", Slope = ",signif(fit$coef[[2]], 2),
                     ", P = ",signif(summary(fit)$coef[2,4], 2)),
       x = "Saturated Fat (grams/day)",
       y = "Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
  theme(text = element_text(size = 13),
        plot.title = element_text(size = 20),
           axis.title = element_text(size = 18),
           axis.text = element_text(size = 15))
}

ggplotRegression_c_sfat(mod_sfat_c)

c_sfat_reg <- ggplotRegression_c_sfat(mod_sfat_c)

# Partial regression 

# Look at all predictors
plot(allEffects(mod_sfat_c, residuals = T)) 

eff_sfat_sfat <- plot(allEffects(mod_sfat_c, residuals = T), 
     selection = 1, 
     main = 'Partial Regression Recent Saturated Fat Intake vs. Subclinical Calprotectin', 
     xlab = 'Saturated Fat (grams/day)', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_sfat_age <- plot(allEffects(mod_sfat_c, residuals = T), 
     selection = 2, 
     main = 'Partial Regression for Age (Recent Saturated Fat Intake vs. Subclinical Calprotectin)', 
     xlab = 'Age (years)', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_sfat_sex <- plot(allEffects(mod_sfat_c, residuals = T), 
     selection = 3, 
     main = 'Partial Regression for Sex (Recent Saturated Fat Intake vs. Subclinical Calprotectin)', 
     xlab = 'Sex', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_sfat_bmi <- plot(allEffects(mod_sfat_c, residuals = T), 
     selection = 4, 
     main = 'Partial Regression for BMI (Recent Saturated Fat Intake vs. Subclinical Calprotectin)', 
     xlab = expression('BMI (kg/m'^2*')'),
     ylab = 'Transformed Calprotectin (ln(x + 1)')

# Grid and save 

fig4_par_sfat <- ggarrange(eff_sfat_sfat, eff_sfat_age, eff_sfat_sex, eff_sfat_bmi,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/fig4_par_sfat.jpg', plot = fig4_par_sfat, device = 'jpeg', dpi = 300, width = 20, height = 10)


```


```{r asa24-hei}

# Calprotectin

mod_hei_asa24_totalscore_c <- lm(clpn_ln ~ hei_asa24_totalscore + age + sex + bmi_final, data = df_c)
summary(mod_hei_asa24_totalscore_c) # NS

# make the regression plot 

ggplotRegression_c_hei_asa24_totalscore <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue") +
  labs(title = "Recent HEI Score vs. Subclinical Calprotectin (n = 253)",
         subtitle = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 2),
                     ", Slope = ",signif(fit$coef[[2]], 2),
                     ", P = ",signif(summary(fit)$coef[2,4], 2)),
       x = "Total Healthy Eating Index Score",
       y = "Transformed Calprotectin (ln(x + 1))") +
  theme_bw() + 
  theme(text = element_text(size = 13),
        plot.title = element_text(size = 20),
           axis.title = element_text(size = 18),
           axis.text = element_text(size = 15))
}

ggplotRegression_c_hei_asa24_totalscore(mod_hei_asa24_totalscore_c)

c_hei_asa24_totalscore_reg <- ggplotRegression_c_hei_asa24_totalscore(mod_hei_asa24_totalscore_c)


# Partial regression 

# Look at all predictors
plot(allEffects(mod_hei_asa24_totalscore_c, residuals = T)) 

eff_hei_asa24_totalscore_hei_asa24_totalscore <- plot(allEffects(mod_hei_asa24_totalscore_c, residuals = T), 
     selection = 1, 
     main = 'Partial Regression Recent HEI Score vs. Subclinical Calprotectin', 
     xlab = 'Total Healthy Eating Index Score', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_hei_asa24_totalscore_age <- plot(allEffects(mod_hei_asa24_totalscore_c, residuals = T), 
     selection = 2, 
     main = 'Partial Regression for Age (Recent HEI Score vs. Subclinical Calprotectin)', 
     xlab = 'Age (years)', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_hei_asa24_totalscore_sex <- plot(allEffects(mod_hei_asa24_totalscore_c, residuals = T), 
     selection = 3, 
     main = 'Partial Regression for Sex (Recent HEI Score vs. Subclinical Calprotectin)', 
     xlab = 'Sex', 
     ylab = 'Transformed Calprotectin (ln(x + 1)')

eff_hei_asa24_totalscore_bmi <- plot(allEffects(mod_hei_asa24_totalscore_c, residuals = T), 
     selection = 4, 
     main = 'Partial Regression for BMI (Recent HEI Score vs. Subclinical Calprotectin)', 
     xlab = expression('BMI (kg/m'^2*')'),
     ylab = 'Transformed Calprotectin (ln(x + 1)')

# Grid and save 

fig4_par_hei_asa24_totalscore <- ggarrange(eff_hei_asa24_totalscore_hei_asa24_totalscore, eff_hei_asa24_totalscore_age, eff_hei_asa24_totalscore_sex, eff_hei_asa24_totalscore_bmi,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/fig4_par_hei_asa24_totalscore.jpg', plot = fig4_par_hei_asa24_totalscore, device = 'jpeg', dpi = 300, width = 20, height = 10)


```



```{r grid-save}

# Grid and save: 

fig4 <- ggarrange(c_fib_reg, c_leg_reg, c_sfat_reg, c_hei_asa24_totalscore_reg,
                      labels = c("A", "B", "C", "D"),
                      nrow = 2, ncol = 2)

ggsave(filename = '/Users/yasmine.bouzid/Documents/GitHub/diet_guthealth/plots/fig4.jpg', plot = fig4, device = 'jpeg', dpi = 300, width = 20, height = 10)

```

